/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as BrandLogoRouteImport } from './routes/brand-logo'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedTrucksRouteImport } from './routes/_authenticated/trucks'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedReportRouteImport } from './routes/_authenticated/report'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedParkingRouteImport } from './routes/_authenticated/parking'
import { Route as AuthenticatedMaintenanceRouteImport } from './routes/_authenticated/maintenance'
import { Route as AuthenticatedLogbookRouteImport } from './routes/_authenticated/logbook'
import { Route as AuthenticatedLoadsRouteImport } from './routes/_authenticated/loads'
import { Route as AuthenticatedInspectionsRouteImport } from './routes/_authenticated/inspections'
import { Route as AuthenticatedIftaRouteImport } from './routes/_authenticated/ifta'
import { Route as AuthenticatedHosRouteImport } from './routes/_authenticated/hos'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedHazardMapRouteImport } from './routes/_authenticated/hazard-map'
import { Route as AuthenticatedFuelRouteImport } from './routes/_authenticated/fuel'
import { Route as AuthenticatedFleetProfitabilityRouteImport } from './routes/_authenticated/fleet-profitability'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedDriverPerformanceRouteImport } from './routes/_authenticated/driver-performance'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDispatchRouteImport } from './routes/_authenticated/dispatch'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCompanyRouteImport } from './routes/_authenticated/company'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedTrucksIndexRouteImport } from './routes/_authenticated/trucks.index'
import { Route as AuthenticatedLoadsIndexRouteImport } from './routes/_authenticated/loads.index'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as AuthenticatedTrucksVehicleUnitRouteImport } from './routes/_authenticated/trucks.$vehicleUnit'
import { Route as AuthenticatedLoadsHistoryRouteImport } from './routes/_authenticated/loads.history'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminPlatformRouteImport } from './routes/_authenticated/admin/platform'
import { Route as AuthenticatedAdminModerationRouteImport } from './routes/_authenticated/admin/moderation'
import { Route as AuthenticatedAdminErrorLogsRouteImport } from './routes/_authenticated/admin/error-logs'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandLogoRoute = BrandLogoRouteImport.update({
  id: '/brand-logo',
  path: '/brand-logo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrucksRoute = AuthenticatedTrucksRouteImport.update({
  id: '/trucks',
  path: '/trucks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportRoute = AuthenticatedReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParkingRoute = AuthenticatedParkingRouteImport.update({
  id: '/parking',
  path: '/parking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaintenanceRoute =
  AuthenticatedMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLogbookRoute = AuthenticatedLogbookRouteImport.update({
  id: '/logbook',
  path: '/logbook',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLoadsRoute = AuthenticatedLoadsRouteImport.update({
  id: '/loads',
  path: '/loads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInspectionsRoute =
  AuthenticatedInspectionsRouteImport.update({
    id: '/inspections',
    path: '/inspections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIftaRoute = AuthenticatedIftaRouteImport.update({
  id: '/ifta',
  path: '/ifta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHosRoute = AuthenticatedHosRouteImport.update({
  id: '/hos',
  path: '/hos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHazardMapRoute = AuthenticatedHazardMapRouteImport.update({
  id: '/hazard-map',
  path: '/hazard-map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFuelRoute = AuthenticatedFuelRouteImport.update({
  id: '/fuel',
  path: '/fuel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFleetProfitabilityRoute =
  AuthenticatedFleetProfitabilityRouteImport.update({
    id: '/fleet-profitability',
    path: '/fleet-profitability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDriverPerformanceRoute =
  AuthenticatedDriverPerformanceRouteImport.update({
    id: '/driver-performance',
    path: '/driver-performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDispatchRoute = AuthenticatedDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompanyRoute = AuthenticatedCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrucksIndexRoute =
  AuthenticatedTrucksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTrucksRoute,
  } as any)
const AuthenticatedLoadsIndexRoute = AuthenticatedLoadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedLoadsRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrucksVehicleUnitRoute =
  AuthenticatedTrucksVehicleUnitRouteImport.update({
    id: '/$vehicleUnit',
    path: '/$vehicleUnit',
    getParentRoute: () => AuthenticatedTrucksRoute,
  } as any)
const AuthenticatedLoadsHistoryRoute =
  AuthenticatedLoadsHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedLoadsRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminPlatformRoute =
  AuthenticatedAdminPlatformRouteImport.update({
    id: '/admin/platform',
    path: '/admin/platform',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminModerationRoute =
  AuthenticatedAdminModerationRouteImport.update({
    id: '/admin/moderation',
    path: '/admin/moderation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminErrorLogsRoute =
  AuthenticatedAdminErrorLogsRouteImport.update({
    id: '/admin/error-logs',
    path: '/admin/error-logs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/brand-logo': typeof BrandLogoRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/company': typeof AuthenticatedCompanyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dispatch': typeof AuthenticatedDispatchRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/driver-performance': typeof AuthenticatedDriverPerformanceRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/fleet-profitability': typeof AuthenticatedFleetProfitabilityRoute
  '/fuel': typeof AuthenticatedFuelRoute
  '/hazard-map': typeof AuthenticatedHazardMapRoute
  '/help': typeof AuthenticatedHelpRoute
  '/hos': typeof AuthenticatedHosRoute
  '/ifta': typeof AuthenticatedIftaRoute
  '/inspections': typeof AuthenticatedInspectionsRoute
  '/loads': typeof AuthenticatedLoadsRouteWithChildren
  '/logbook': typeof AuthenticatedLogbookRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/parking': typeof AuthenticatedParkingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/report': typeof AuthenticatedReportRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/trucks': typeof AuthenticatedTrucksRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/admin/error-logs': typeof AuthenticatedAdminErrorLogsRoute
  '/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/admin/platform': typeof AuthenticatedAdminPlatformRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/loads/history': typeof AuthenticatedLoadsHistoryRoute
  '/trucks/$vehicleUnit': typeof AuthenticatedTrucksVehicleUnitRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/loads/': typeof AuthenticatedLoadsIndexRoute
  '/trucks/': typeof AuthenticatedTrucksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/brand-logo': typeof BrandLogoRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/company': typeof AuthenticatedCompanyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dispatch': typeof AuthenticatedDispatchRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/driver-performance': typeof AuthenticatedDriverPerformanceRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/fleet-profitability': typeof AuthenticatedFleetProfitabilityRoute
  '/fuel': typeof AuthenticatedFuelRoute
  '/hazard-map': typeof AuthenticatedHazardMapRoute
  '/help': typeof AuthenticatedHelpRoute
  '/hos': typeof AuthenticatedHosRoute
  '/ifta': typeof AuthenticatedIftaRoute
  '/inspections': typeof AuthenticatedInspectionsRoute
  '/logbook': typeof AuthenticatedLogbookRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/parking': typeof AuthenticatedParkingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/report': typeof AuthenticatedReportRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/api/chat': typeof ApiChatRoute
  '/admin/error-logs': typeof AuthenticatedAdminErrorLogsRoute
  '/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/admin/platform': typeof AuthenticatedAdminPlatformRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/loads/history': typeof AuthenticatedLoadsHistoryRoute
  '/trucks/$vehicleUnit': typeof AuthenticatedTrucksVehicleUnitRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/loads': typeof AuthenticatedLoadsIndexRoute
  '/trucks': typeof AuthenticatedTrucksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/brand-logo': typeof BrandLogoRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/company': typeof AuthenticatedCompanyRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dispatch': typeof AuthenticatedDispatchRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/driver-performance': typeof AuthenticatedDriverPerformanceRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/fleet-profitability': typeof AuthenticatedFleetProfitabilityRoute
  '/_authenticated/fuel': typeof AuthenticatedFuelRoute
  '/_authenticated/hazard-map': typeof AuthenticatedHazardMapRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/hos': typeof AuthenticatedHosRoute
  '/_authenticated/ifta': typeof AuthenticatedIftaRoute
  '/_authenticated/inspections': typeof AuthenticatedInspectionsRoute
  '/_authenticated/loads': typeof AuthenticatedLoadsRouteWithChildren
  '/_authenticated/logbook': typeof AuthenticatedLogbookRoute
  '/_authenticated/maintenance': typeof AuthenticatedMaintenanceRoute
  '/_authenticated/parking': typeof AuthenticatedParkingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/report': typeof AuthenticatedReportRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/trucks': typeof AuthenticatedTrucksRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/admin/error-logs': typeof AuthenticatedAdminErrorLogsRoute
  '/_authenticated/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/_authenticated/admin/platform': typeof AuthenticatedAdminPlatformRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/loads/history': typeof AuthenticatedLoadsHistoryRoute
  '/_authenticated/trucks/$vehicleUnit': typeof AuthenticatedTrucksVehicleUnitRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/_authenticated/loads/': typeof AuthenticatedLoadsIndexRoute
  '/_authenticated/trucks/': typeof AuthenticatedTrucksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/brand-logo'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/alerts'
    | '/assistant'
    | '/billing'
    | '/company'
    | '/dashboard'
    | '/dispatch'
    | '/documents'
    | '/driver-performance'
    | '/expenses'
    | '/fleet-profitability'
    | '/fuel'
    | '/hazard-map'
    | '/help'
    | '/hos'
    | '/ifta'
    | '/inspections'
    | '/loads'
    | '/logbook'
    | '/maintenance'
    | '/parking'
    | '/profile'
    | '/report'
    | '/reports'
    | '/trucks'
    | '/api/chat'
    | '/admin/error-logs'
    | '/admin/moderation'
    | '/admin/platform'
    | '/admin/users'
    | '/loads/history'
    | '/trucks/$vehicleUnit'
    | '/api/public/stripe-webhook'
    | '/loads/'
    | '/trucks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/brand-logo'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/alerts'
    | '/assistant'
    | '/billing'
    | '/company'
    | '/dashboard'
    | '/dispatch'
    | '/documents'
    | '/driver-performance'
    | '/expenses'
    | '/fleet-profitability'
    | '/fuel'
    | '/hazard-map'
    | '/help'
    | '/hos'
    | '/ifta'
    | '/inspections'
    | '/logbook'
    | '/maintenance'
    | '/parking'
    | '/profile'
    | '/report'
    | '/reports'
    | '/api/chat'
    | '/admin/error-logs'
    | '/admin/moderation'
    | '/admin/platform'
    | '/admin/users'
    | '/loads/history'
    | '/trucks/$vehicleUnit'
    | '/api/public/stripe-webhook'
    | '/loads'
    | '/trucks'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/brand-logo'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/alerts'
    | '/_authenticated/assistant'
    | '/_authenticated/billing'
    | '/_authenticated/company'
    | '/_authenticated/dashboard'
    | '/_authenticated/dispatch'
    | '/_authenticated/documents'
    | '/_authenticated/driver-performance'
    | '/_authenticated/expenses'
    | '/_authenticated/fleet-profitability'
    | '/_authenticated/fuel'
    | '/_authenticated/hazard-map'
    | '/_authenticated/help'
    | '/_authenticated/hos'
    | '/_authenticated/ifta'
    | '/_authenticated/inspections'
    | '/_authenticated/loads'
    | '/_authenticated/logbook'
    | '/_authenticated/maintenance'
    | '/_authenticated/parking'
    | '/_authenticated/profile'
    | '/_authenticated/report'
    | '/_authenticated/reports'
    | '/_authenticated/trucks'
    | '/api/chat'
    | '/_authenticated/admin/error-logs'
    | '/_authenticated/admin/moderation'
    | '/_authenticated/admin/platform'
    | '/_authenticated/admin/users'
    | '/_authenticated/loads/history'
    | '/_authenticated/trucks/$vehicleUnit'
    | '/api/public/stripe-webhook'
    | '/_authenticated/loads/'
    | '/_authenticated/trucks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BrandLogoRoute: typeof BrandLogoRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-logo': {
      id: '/brand-logo'
      path: '/brand-logo'
      fullPath: '/brand-logo'
      preLoaderRoute: typeof BrandLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trucks': {
      id: '/_authenticated/trucks'
      path: '/trucks'
      fullPath: '/trucks'
      preLoaderRoute: typeof AuthenticatedTrucksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report': {
      id: '/_authenticated/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AuthenticatedReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parking': {
      id: '/_authenticated/parking'
      path: '/parking'
      fullPath: '/parking'
      preLoaderRoute: typeof AuthenticatedParkingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance': {
      id: '/_authenticated/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthenticatedMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logbook': {
      id: '/_authenticated/logbook'
      path: '/logbook'
      fullPath: '/logbook'
      preLoaderRoute: typeof AuthenticatedLogbookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loads': {
      id: '/_authenticated/loads'
      path: '/loads'
      fullPath: '/loads'
      preLoaderRoute: typeof AuthenticatedLoadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspections': {
      id: '/_authenticated/inspections'
      path: '/inspections'
      fullPath: '/inspections'
      preLoaderRoute: typeof AuthenticatedInspectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ifta': {
      id: '/_authenticated/ifta'
      path: '/ifta'
      fullPath: '/ifta'
      preLoaderRoute: typeof AuthenticatedIftaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hos': {
      id: '/_authenticated/hos'
      path: '/hos'
      fullPath: '/hos'
      preLoaderRoute: typeof AuthenticatedHosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hazard-map': {
      id: '/_authenticated/hazard-map'
      path: '/hazard-map'
      fullPath: '/hazard-map'
      preLoaderRoute: typeof AuthenticatedHazardMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fuel': {
      id: '/_authenticated/fuel'
      path: '/fuel'
      fullPath: '/fuel'
      preLoaderRoute: typeof AuthenticatedFuelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fleet-profitability': {
      id: '/_authenticated/fleet-profitability'
      path: '/fleet-profitability'
      fullPath: '/fleet-profitability'
      preLoaderRoute: typeof AuthenticatedFleetProfitabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/driver-performance': {
      id: '/_authenticated/driver-performance'
      path: '/driver-performance'
      fullPath: '/driver-performance'
      preLoaderRoute: typeof AuthenticatedDriverPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dispatch': {
      id: '/_authenticated/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof AuthenticatedDispatchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/company': {
      id: '/_authenticated/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof AuthenticatedCompanyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trucks/': {
      id: '/_authenticated/trucks/'
      path: '/'
      fullPath: '/trucks/'
      preLoaderRoute: typeof AuthenticatedTrucksIndexRouteImport
      parentRoute: typeof AuthenticatedTrucksRoute
    }
    '/_authenticated/loads/': {
      id: '/_authenticated/loads/'
      path: '/'
      fullPath: '/loads/'
      preLoaderRoute: typeof AuthenticatedLoadsIndexRouteImport
      parentRoute: typeof AuthenticatedLoadsRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trucks/$vehicleUnit': {
      id: '/_authenticated/trucks/$vehicleUnit'
      path: '/$vehicleUnit'
      fullPath: '/trucks/$vehicleUnit'
      preLoaderRoute: typeof AuthenticatedTrucksVehicleUnitRouteImport
      parentRoute: typeof AuthenticatedTrucksRoute
    }
    '/_authenticated/loads/history': {
      id: '/_authenticated/loads/history'
      path: '/history'
      fullPath: '/loads/history'
      preLoaderRoute: typeof AuthenticatedLoadsHistoryRouteImport
      parentRoute: typeof AuthenticatedLoadsRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/platform': {
      id: '/_authenticated/admin/platform'
      path: '/admin/platform'
      fullPath: '/admin/platform'
      preLoaderRoute: typeof AuthenticatedAdminPlatformRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/moderation': {
      id: '/_authenticated/admin/moderation'
      path: '/admin/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AuthenticatedAdminModerationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/error-logs': {
      id: '/_authenticated/admin/error-logs'
      path: '/admin/error-logs'
      fullPath: '/admin/error-logs'
      preLoaderRoute: typeof AuthenticatedAdminErrorLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedLoadsRouteChildren {
  AuthenticatedLoadsHistoryRoute: typeof AuthenticatedLoadsHistoryRoute
  AuthenticatedLoadsIndexRoute: typeof AuthenticatedLoadsIndexRoute
}

const AuthenticatedLoadsRouteChildren: AuthenticatedLoadsRouteChildren = {
  AuthenticatedLoadsHistoryRoute: AuthenticatedLoadsHistoryRoute,
  AuthenticatedLoadsIndexRoute: AuthenticatedLoadsIndexRoute,
}

const AuthenticatedLoadsRouteWithChildren =
  AuthenticatedLoadsRoute._addFileChildren(AuthenticatedLoadsRouteChildren)

interface AuthenticatedTrucksRouteChildren {
  AuthenticatedTrucksVehicleUnitRoute: typeof AuthenticatedTrucksVehicleUnitRoute
  AuthenticatedTrucksIndexRoute: typeof AuthenticatedTrucksIndexRoute
}

const AuthenticatedTrucksRouteChildren: AuthenticatedTrucksRouteChildren = {
  AuthenticatedTrucksVehicleUnitRoute: AuthenticatedTrucksVehicleUnitRoute,
  AuthenticatedTrucksIndexRoute: AuthenticatedTrucksIndexRoute,
}

const AuthenticatedTrucksRouteWithChildren =
  AuthenticatedTrucksRoute._addFileChildren(AuthenticatedTrucksRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedCompanyRoute: typeof AuthenticatedCompanyRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDispatchRoute: typeof AuthenticatedDispatchRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedDriverPerformanceRoute: typeof AuthenticatedDriverPerformanceRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedFleetProfitabilityRoute: typeof AuthenticatedFleetProfitabilityRoute
  AuthenticatedFuelRoute: typeof AuthenticatedFuelRoute
  AuthenticatedHazardMapRoute: typeof AuthenticatedHazardMapRoute
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedHosRoute: typeof AuthenticatedHosRoute
  AuthenticatedIftaRoute: typeof AuthenticatedIftaRoute
  AuthenticatedInspectionsRoute: typeof AuthenticatedInspectionsRoute
  AuthenticatedLoadsRoute: typeof AuthenticatedLoadsRouteWithChildren
  AuthenticatedLogbookRoute: typeof AuthenticatedLogbookRoute
  AuthenticatedMaintenanceRoute: typeof AuthenticatedMaintenanceRoute
  AuthenticatedParkingRoute: typeof AuthenticatedParkingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportRoute: typeof AuthenticatedReportRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedTrucksRoute: typeof AuthenticatedTrucksRouteWithChildren
  AuthenticatedAdminErrorLogsRoute: typeof AuthenticatedAdminErrorLogsRoute
  AuthenticatedAdminModerationRoute: typeof AuthenticatedAdminModerationRoute
  AuthenticatedAdminPlatformRoute: typeof AuthenticatedAdminPlatformRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedCompanyRoute: AuthenticatedCompanyRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDispatchRoute: AuthenticatedDispatchRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedDriverPerformanceRoute: AuthenticatedDriverPerformanceRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedFleetProfitabilityRoute: AuthenticatedFleetProfitabilityRoute,
  AuthenticatedFuelRoute: AuthenticatedFuelRoute,
  AuthenticatedHazardMapRoute: AuthenticatedHazardMapRoute,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedHosRoute: AuthenticatedHosRoute,
  AuthenticatedIftaRoute: AuthenticatedIftaRoute,
  AuthenticatedInspectionsRoute: AuthenticatedInspectionsRoute,
  AuthenticatedLoadsRoute: AuthenticatedLoadsRouteWithChildren,
  AuthenticatedLogbookRoute: AuthenticatedLogbookRoute,
  AuthenticatedMaintenanceRoute: AuthenticatedMaintenanceRoute,
  AuthenticatedParkingRoute: AuthenticatedParkingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportRoute: AuthenticatedReportRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedTrucksRoute: AuthenticatedTrucksRouteWithChildren,
  AuthenticatedAdminErrorLogsRoute: AuthenticatedAdminErrorLogsRoute,
  AuthenticatedAdminModerationRoute: AuthenticatedAdminModerationRoute,
  AuthenticatedAdminPlatformRoute: AuthenticatedAdminPlatformRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BrandLogoRoute: BrandLogoRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
